// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_buy_the_earth = "CgkIrdTOtaYPEAIQDQ"; // <GPGSID>
        public const string achievement_you_did_it_she_is_proud_of_you = "CgkIrdTOtaYPEAIQBw"; // <GPGSID>
        public const string achievement_mans_best_friend = "CgkIrdTOtaYPEAIQBQ"; // <GPGSID>
        public const string achievement_the_leprechaun = "CgkIrdTOtaYPEAIQCg"; // <GPGSID>
        public const string leaderboard_total_money_made_in_mil = "CgkIrdTOtaYPEAIQEA"; // <GPGSID>
        public const string achievement_logacy_of_floppa = "CgkIrdTOtaYPEAIQDw"; // <GPGSID>
        public const string achievement_the_idol = "CgkIrdTOtaYPEAIQCQ"; // <GPGSID>
        public const string achievement_milk_man = "CgkIrdTOtaYPEAIQBg"; // <GPGSID>
        public const string leaderboard_flushed_in_mil = "CgkIrdTOtaYPEAIQEQ"; // <GPGSID>
        public const string achievement_its_a_zoo = "CgkIrdTOtaYPEAIQCA"; // <GPGSID>
        public const string achievement_money_can_buy_happiness = "CgkIrdTOtaYPEAIQCw"; // <GPGSID>
        public const string achievement_time_lord = "CgkIrdTOtaYPEAIQDg"; // <GPGSID>
        public const string achievement_touchy = "CgkIrdTOtaYPEAIQDA"; // <GPGSID>

}

